JohanCorner/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JohanCorner.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

JohanCorner/Controllers/TimeChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JohanCorner.Controllers
{
    public class TimeChartController : Controller
    {
        //
        // GET: /TimeChart/

        public ActionResult Index()
        {
            return View();
        }

    }
}

JohanCorner/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Уголок Йохана</h2>

JohanCorner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/jquery-1.9.1.min.js")
    @Scripts.Render("~/Scripts/jquery-ui-1.9.2.custom.min.js")
    @Scripts.Render("~/Scripts/spin.min.js")
</head>
    <body>
        <nav>
            <ul class="menu">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Time Chart", "Index", "TimeChart")</li>
            </ul>
        </nav>
        @RenderBody()

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

JohanCorner/Views/TimeChart/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Time Chart</h2>
<table id="sheetTable">
    <tr>
        @for(int col = 0; col < 24; col++)
        {
            <td width="20" colspan="2">
                <label id="column-header-@col" class="column-header">@col</label>
            </td>
        }
    </tr>
    @for(int row = 0; row < 30; row++)
    {
        <tr height="20">
            @for(int col = 0; col < 24*2; col++)
            {
                <td class="cell-@(col/2)" width="20"></td>
            }
        </tr>
    }

</table>
@Scripts.Render("~/Scripts/TimeSheet.js")
@*@Scripts.Render("~/Scripts/hltable.js");
<script type="text/javascript">
    
    highlightTableCells("sheetTable", "hoverRow", "clickedRow");

</script>*@